[theme]
inherit = basic
stylesheet = typlog.css
sidebars = logo.html, github.html, globaltoc.html, searchbox.html

[options]
version = 0.8.0
color =
logo =
logo_name =
description =
github_user =
github_repo =
analytics_id =
canonical_url =
twitter =
og_image =
meta_html =
warning =
